USE [master]
GO

/****** Object:  Database [SportsBuddyDB]    Script Date: 8/4/2021 10:22:14 AM ******/
CREATE DATABASE [SportsBuddyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SportsBuddyDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SportsBuddyDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SportsBuddyDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SportsBuddyDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SportsBuddyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SportsBuddyDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SportsBuddyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SportsBuddyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SportsBuddyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SportsBuddyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SportsBuddyDB] SET  MULTI_USER 
GO

ALTER DATABASE [SportsBuddyDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SportsBuddyDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SportsBuddyDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SportsBuddyDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SportsBuddyDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SportsBuddyDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SportsBuddyDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SportsBuddyDB] SET  READ_WRITE 
GO

USE [SportsBuddyDB]
GO

